function [display] = InstructionLines(colorName1,colorName2,arrowside1,arrowside2,inst,display)

if inst==1
  DrawFormattedText(display.windowPtr,  sprintf('%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s', ...
        ['If the presented number is ' , colorName1],...
        'then you have to decide whether it is odd or even.',...
        'If the presented number in that trial is an EVEN number',...
        ['you need to press the ', arrowside1 ],...
        'if it is an ODD number',...
        ['you need to press the ' ,  arrowside2 ],...
        '(Press a key to try an example.)'), 'center', 'center', [255 255 255], [100],[],[],[1.25]);
elseif inst==2

 DrawFormattedText(display.windowPtr, sprintf('%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s', ...
        ['Otherwise, if the presented number is ' , colorName2], ...
        'then you have to decide whether it is smaller or greater than 5.',...
        'If the presented number in that trial is less than 5,',...
        ['you need to press the ' , arrowside1],...
        ['if it is greater than 5, you need to press the ' , arrowside2],...
        '(Press a key to try an example.)'), 'center', 'center', [255 255 255], [100],[],[],[1.25]);
elseif inst==3
    DrawFormattedText(display.windowPtr, sprintf('%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s', ...
        ['Quick summary : if the color of number is ', colorName1], ...
        'you decide whether it is odd or even.',...
        ['If the presented number is odd, press the ', arrowside2],...
        ['if it is an even number, press the ', arrowside1],...
        ['If the color of the number is ' ,colorName2],...
        'decide whether it is smaller or greater than 5.',...
        'If the presented number is less than 5,',...
        ['press the ', arrowside2],...
        ['if it is greater than 5, press the ', arrowside1],...
        'Press a key to start the practice.'), 'center', 'center', [255 255 255], [100],[],[],[1.25]);
end