function [display] = InstructionLines(colorName1,colorName2,arrowside1,arrowside2,inst,display)

if inst==1

  DrawFormattedText(display.windowPtr,  sprintf('%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s', ...
        ['If the presented number is ' , colorName1],...
        'then you have to decide whether it is odd or even.',...
        '', ...
        'If the presented number on that trial is an EVEN number',...
        ['you need to press the ', arrowside1 ],...
        '', ...
        'If it is an ODD number',...
        ['you need to press the ' ,  arrowside2 ],...
        '', ...
        '(Press a key for an illustration.)'), 'center', 'center', [255 255 255], [100],[],[],[1.5]);
elseif inst==2
 DrawFormattedText(display.windowPtr, sprintf('%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s', ...
        ['Otherwise, if the presented number is ' , colorName2], ...
        'then you have to decide whether it is smaller or greater than 5.',...
         '', ...
        'If the presented number on that trial is LESS than 5,',...
        'you need to press the LEFT ARROW (<-)' ,...
        '', ...
        'If it is GREATER than 5, you need to press the RIGHT ARROW (->)',...
         '', ...
        '(Press a key for an illustration.)'), 'center', 'center', [255 255 255], [100],[],[],[1.5]);
elseif inst==3

    DrawFormattedText(display.windowPtr, sprintf('%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s', ...
        ['Quick summary : if the color of number is ', colorName1  ], ...
        'you decide whether it is ODD or EVEN.',...
        '', ...
        ['If the presented number is ODD, press the ', arrowside2],...
        ['if it is an EVEN number, press the ', arrowside1],...
        '', ...
        ['If the color of the number is ' ,colorName2],...
        'decide whether it is smaller or greater than 5.',...
        '', ...
        'If the presented number is less than 5,',...
        'press the LEFT ARROW (<-) ',...
        'if it is greater than 5, press the RIGHT ARROW (->)',...
        '', ...
        'Press a key to review the illustrations.'), 'center', 'center', [255 255 255], [100],[],[],[1.5]);
end